version: "3.8"

services:
  db:
    image: pgautoupgrade/pgautoupgrade #postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    healthcheck: # Проверка работоспособности базы данных
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on: # Зависимость от базы данных
      db:
        condition: service_healthy # Ждать, пока база данных не станет здоровой
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db # Имя сервиса базы данных
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
