# Generated by Django 5.1.6 on 2025-02-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomicalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('object_type', models.CharField(max_length=100)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
